#!/usr/bin/env python3
"""Record the config keys we changed, without secrets.

Compares each live config in /opt/wow/server/etc (worldserver, authserver, modules/*) with the .conf.dist
installed beside it and writes conf/<name>.overrides: every key whose value differs from the .dist, or that
the .dist doesn't have. Values of secret keys (database connection strings, tokens, passwords, API keys)
are written as ${REDACTED}. Run after changing a live config, then commit conf/.

Usage: python3 ops/scripts/conf-overrides.py [--etc /opt/wow/server/etc]
"""
import argparse
import glob
import os
import re

SECRET = re.compile(r"(DatabaseInfo|Password|Token|ApiKey|Secret)", re.I)

# Keys whose value is a fact about THIS MACHINE rather than a decision about the realm (plan 23 W5).
# conf-apply.py fills these back in from site/site.env, and refuses to write a conf that still contains
# a ${...} it could not resolve -- a half-substituted config is worse than no config.
SITE = {
    "DataDir": "${DATA_DIR}",
    "LogsDir": "${SERVER_LOGS}",
    "MapUpdate.Threads": "${MAP_THREADS}",
    "AiPlayerbot.MinRandomBots": "${BOT_MIN}",
    "AiPlayerbot.MaxRandomBots": "${BOT_MAX}",
    "Dashboard.Bind": "${DASHBOARD_BIND}",
    "Dashboard.DataRoot": "${DATA_DIR}/dashboard-data",
    "AuctionHouseBot.Merchants.Account": "${MERCHANT_ACCOUNT}",
    "AuctionHouseBot.Merchants.Characters": "${MERCHANT_CHARACTERS}",
    "AuctionHouseBot.AllowedItemIDsFile": "${DATA_DIR}/economy/allowed-items.txt",
    "OllamaChat.Url": "${ROUTER_URL}",
    "OllamaChat.MaxConcurrentQueries": "${CHAT_CONCURRENCY}",
    "OllamaChat.RAGDataPath": "${DATA_DIR}/ollama-rag/",
}


def placehold(key, value):
    """The value to record: a secret redacted, a site fact as its placeholder, anything else as it is."""
    if SECRET.search(key):
        return "${REDACTED}"
    if key in SITE:
        # Keep the .conf's own quoting: DataDir and LogsDir are quoted, the rest are bare.
        return f'"{SITE[key]}"' if value.startswith('"') else SITE[key]
    return value
LINE = re.compile(r"^\s*([A-Za-z0-9_.]+)\s*=\s*(.*?)\s*$")
REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))


def keys(path):
    found = {}
    if not os.path.exists(path):
        return found
    for raw in open(path, encoding="utf-8", errors="replace"):
        if raw.lstrip().startswith("#"):
            continue
        m = LINE.match(raw)
        if m:
            found[m.group(1)] = m.group(2)
    return found


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--etc", default="/opt/wow/server/etc")
    args = ap.parse_args()
    out_dir = os.path.join(REPO, "conf")
    os.makedirs(out_dir, exist_ok=True)
    for live in sorted(glob.glob(os.path.join(args.etc, "*.conf")) + glob.glob(os.path.join(args.etc, "modules", "*.conf"))):
        dist = keys(live + ".dist")
        changed = [(k, v) for k, v in keys(live).items() if dist.get(k) != v]
        name = os.path.basename(live)[:-len(".conf")]
        target = os.path.join(out_dir, name + ".overrides")
        with open(target, "w", encoding="utf-8") as f:
            f.write(f"# {os.path.relpath(live, args.etc)}: keys that differ from the installed .conf.dist\n")
            # This file is rewritten wholesale every run, so a comment added by hand does not survive it.
            # Why a key is set the way it is belongs in plans/ or docs/GUIDE.md, which outlive the value.
            f.write("# Generated by ops/scripts/conf-overrides.py — do not edit; notes here are lost on the\n"
                    "# next run. ${PLACEHOLDERS} are filled in by ops/scripts/conf-apply.py from site/.\n")
            for k, v in changed:
                f.write(f"{k} = {placehold(k, v)}\n")
        print(f"{name}: {len(changed)} changed keys")


if __name__ == "__main__":
    main()
