-- Canonical lore for a Headless DM realm (acore_characters).
-- Generated by the LLM fleet (/opt/wow/lore/gen_backstories.py); projected into
-- mod-ollama-chat (personality templates) and the guild table (info/motd).
-- These tables are the source of truth: re-project from here, never edit the
-- projections by hand.

CREATE TABLE IF NOT EXISTS lore_guild (
    guildid      INT UNSIGNED NOT NULL,
    history      TEXT         NOT NULL COMMENT 'Full in-world history of the company',
    charter      VARCHAR(500) NOT NULL COMMENT 'Public description, projected to guild.info',
    motto        VARCHAR(128) NOT NULL COMMENT 'Current word from the leaders, projected to guild.motd',
    member_roles JSON         NULL     COMMENT '{character name: one-line standing in the company}',
    model        VARCHAR(64)  NOT NULL,
    era          VARCHAR(16)  NOT NULL DEFAULT 'wotlk' COMMENT 'era.py setting the text was written for',
    generated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (guildid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Who is whose (plan 21 §1). An account with no row here has no alts: its characters stay plain real players.
-- Naming a main is what turns the rest of that account's characters into alts. Keyed by account, so nothing
-- hard-codes a name and another player gets alts by getting one row.
CREATE TABLE IF NOT EXISTS player_main (
    account_id INT UNSIGNED NOT NULL,
    main_guid  INT UNSIGNED NOT NULL COMMENT 'The character this account calls its own; its others are alts',
    set_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- One definition of a person's kind, for every service that used to test `username LIKE 'RNDBOT%'`.
-- Bots with lore: 'bot' and 'alt'. Real players: 'main' and 'player'.
CREATE OR REPLACE VIEW person_kind AS
SELECT c.guid, c.account,
       CASE WHEN a.username LIKE 'RNDBOT%' THEN 'bot'
            WHEN pm.main_guid = c.guid     THEN 'main'
            WHEN pm.account_id IS NOT NULL THEN 'alt'
            ELSE 'player' END AS kind,
       pm.main_guid
FROM characters c
JOIN acore_auth.account a ON a.id = c.account
LEFT JOIN player_main pm ON pm.account_id = c.account;

-- What is between an alt and the main it is bound to (plan 21 §3). Written before the backstory, so the
-- backstory can be built around it.
CREATE TABLE IF NOT EXISTS lore_alt (
    guid         INT UNSIGNED NOT NULL COMMENT 'The alt',
    main_guid    INT UNSIGNED NOT NULL,
    kind         VARCHAR(24)  NOT NULL COMMENT 'kin|sworn|debt|mentor|pupil|comrade|retainer|distant',
    pinned       TINYINT      NOT NULL DEFAULT 0 COMMENT '1 = the player chose the kind; never re-rolled',
    bond         TEXT         NOT NULL COMMENT '30-60 words, second person: what is between you',
    sheet_hash   CHAR(40)     NULL     COMMENT 'The lore_main sheet the bond was written from',
    source       TEXT         NULL     COMMENT 'The player''s own words, when a person wrote this (plan 28)',
    model        VARCHAR(64)  NOT NULL,
    era          VARCHAR(16)  NOT NULL DEFAULT 'classic',
    generated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (guid),
    KEY idx_main (main_guid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- The player's own main character (plan 21 §2). No model writes a real player's story or their thoughts;
-- this is the player's own account of themselves, tidied into one in-world paragraph, so that an alt's bond
-- can be written from it. It is never projected into a prompt for the main himself.
CREATE TABLE IF NOT EXISTS lore_main (
    guid       INT UNSIGNED NOT NULL,
    sheet      TEXT         NOT NULL COMMENT 'In-world paragraph about the main, read when writing an alt''s bond',
    source     TEXT         NULL     COMMENT 'The player''s own words, kept so the sheet can be reshaped later',
    sheet_hash CHAR(40)     NULL     COMMENT 'sha1 of sheet; lore_alt.sheet_hash is compared against it (plan 21 §3)',
    model      VARCHAR(64)  NOT NULL,
    era        VARCHAR(16)  NOT NULL DEFAULT 'classic' COMMENT 'era.py setting the text was written for',
    updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (guid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lore_character (
    guid         INT UNSIGNED NOT NULL,
    guildid      INT UNSIGNED NULL     COMMENT 'Guild at generation time; NULL if unguilded',
    temperament  VARCHAR(64)  NOT NULL COMMENT 'Key from mod_ollama_chat_personality_templates',
    backstory    TEXT         NOT NULL COMMENT 'Second-person backstory used in every prompt',
    personality  VARCHAR(400) NULL     COMMENT 'Who they are in any room; every prompt (plan 15)',
    gist         VARCHAR(600) NULL     COMMENT 'The backstory in about 45 words; every prompt',
    motivation   TEXT         NULL     COMMENT 'What they live for, 40-70 words; conversations',
    motivation_short VARCHAR(255) NULL COMMENT 'The motivation in one line; every prompt',
    motivation_kind  VARCHAR(16)  NULL,
    motivation_target JSON        NULL COMMENT '{type: foe|person|place|faction|cause, name}',
    source       TEXT         NULL     COMMENT 'The player''s own words, when a person wrote this (plan 28)',
    -- The working life (plan 33). The trade is read out of character_skills, never invented, so what a
    -- character claims to do is a thing they really have the skill for. The household is written against
    -- the backstory: kin the story buried stay buried.
    craft        VARCHAR(600) NULL     COMMENT 'The work of your hands, ~45 words; read when addressed',
    craft_short  VARCHAR(255) NULL     COMMENT 'The trade in one line; every prompt',
    kin          VARCHAR(600) NULL     COMMENT 'Your people, ~45 words; read when addressed',
    kin_short    VARCHAR(255) NULL     COMMENT 'The household in one line; every prompt',
    model        VARCHAR(64)  NOT NULL,
    era          VARCHAR(16)  NOT NULL DEFAULT 'wotlk' COMMENT 'era.py setting the text was written for',
    generated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (guid),
    KEY idx_guild (guildid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
