-- Quest words (custom wow plans/50 section 6): an errand said the way a person would say it, instead of the
-- name it carries in a quest log.
--
-- Written by services/lore/gen_quest_words.py on the operator's own machine, from the quests this realm has
-- actually touched, and read by mod-ollama-chat wherever a quest is currently named. Lives in
-- acore_characters beside land_words and place_words.
--
-- NOTHING ABOUT AZEROTH IS COMMITTED TO THE REPOSITORY. The quest list comes from this realm's own
-- character_queststatus, the text from the operator's own acore_world, and every phrase is generated here
-- and stored here. Two realms produce two different sets and neither one ships.
--
-- WHY THIS TABLE EXISTS. A quest-log title is a game artefact, like a level number -- plan 32 invariant 1,
-- "in-world words, never figures". Five sites were handing titles straight to the model
-- (events.cpp:602/610, handler.cpp:1205/1288/1293), and it obeyed: three bots announced "The Daughter Who
-- Lived", "the Shadowy Figure business" and "Worgen in the Woods" within seconds of real completions. The
-- titles then reached the permanent memory store, where 7.07% of 85,887 rows already carry one.
--
-- An instruction does not fix this and we have the proof: ChatBotSnapshotTemplate already says "describe
-- things as a person would, never recite figures", and the titles are injected in quotes directly beneath it.

CREATE TABLE IF NOT EXISTS quest_words (
    quest_id   INT UNSIGNED     NOT NULL COMMENT 'quest_template.ID, as ledger_event and the quest log record it',
    era        VARCHAR(16)      NOT NULL COMMENT 'the same errand can read differently in a later age',
    variant    TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'room for more than one phrasing; one is generated by default',
    words      VARCHAR(255)     NOT NULL COMMENT 'How a person names this errand. MUST NOT contain the log title.',
    updated_at DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (quest_id, era, variant),
    KEY by_era (era)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
